[AllowList]
  Regexes = ["yR\\+uWwIZp6ihFgaHV8410b2BxbRt5QiAj1EZx1qj", "eb3692aa10723d1d3fca8a55eb78cbc9318c7a07", "aws_api_key = 'zR\\+uWwIZp6ihFgaHV8410b2BxbRt5QiAj1EZx1qj'", "aws_api_key = 'aR\\+uWwIZp6ihFgaHV8410b2BxbRt5QiAj1EZx1qj'"]
