[AllowList]
  Description = "Allowlisted files"
  Files = ["^\\.?gitleaks.toml$", "(.*?)(jpg|gif|doc|pdf|bin)$", "(go.mod|go.sum)$"]

[[Rules]]
  Description = "AWS Manager ID TESTING TESTING"
  Regex = "(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}"
  File = ""
  Path = ""
  Tags = ["key", "AWS"]
  [Rules.AllowList]
    Description = ""
    Regexes = ["aws_api_credential = 'yR\\+uWwIZp6ihFgaHV8410b2BxbRt5QiAj1EZx1qj'"]

[[Rules]]
  Description = "AWS Secret Key"
  Regex = "(?i)aws(.{0,20})?(?-i)['\\\"][0-9a-zA-Z\\/+]{40}['\\\"]"
  File = ""
  Path = ""
  Tags = ["key", "AWS"]
  [Rules.AllowList]
    Description = ""
    Regexes = ["aws_api_credential = 'yR\\+uWwIZp6ihFgaHV8410b2BxbRt5QiAj1EZx1qj'"]

[[Rules]]
  Description = "AWS MWS key"
  Regex = "amzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
  File = ""
  Path = ""
  Tags = ["key", "AWS", "MWS"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Facebook Secret Key"
  Regex = "(?i)(facebook|fb)(.{0,20})?(?-i)['\\\"][0-9a-f]{32}['\\\"]"
  File = ""
  Path = ""
  Tags = ["key", "Facebook"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Facebook Client ID"
  Regex = "(?i)(facebook|fb)(.{0,20})?['\\\"][0-9]{13,17}['\\\"]"
  File = ""
  Path = ""
  Tags = ["key", "Facebook"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Twitter Secret Key"
  Regex = "(?i)twitter(.{0,20})?[0-9a-z]{35,44}"
  File = ""
  Path = ""
  Tags = ["key", "Twitter"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Twitter Client ID"
  Regex = "(?i)twitter(.{0,20})?[0-9a-z]{18,25}"
  File = ""
  Path = ""
  Tags = ["client", "Twitter"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Github"
  Regex = "(?i)github(.{0,20})?(?-i)[0-9a-zA-Z]{35,40}"
  File = ""
  Path = ""
  Tags = ["key", "Github"]
  [Rules.AllowList]
    Description = ""
    Regexes = ["github = 'eb3692aa10723d1d3fca8a55eb78cbc9318c7a07"]

[[Rules]]
  Description = "LinkedIn Client ID"
  Regex = "(?i)linkedin(.{0,20})?(?-i)[0-9a-z]{12}"
  File = ""
  Path = ""
  Tags = ["client", "LinkedIn"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "LinkedIn Secret Key"
  Regex = "(?i)linkedin(.{0,20})?[0-9a-z]{16}"
  File = ""
  Path = ""
  Tags = ["secret", "LinkedIn"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Slack"
  Regex = "xox[baprs]-([0-9a-zA-Z]{10,48})?"
  File = ""
  Path = ""
  Tags = ["key", "Slack"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Asymmetric Private Key"
  Regex = "-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----"
  File = ""
  Path = ""
  Tags = ["key", "AsymmetricPrivateKey"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Google API key"
  Regex = "AIza[0-9A-Za-z\\\\-_]{35}"
  File = ""
  Path = ""
  Tags = ["key", "Google"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Google (GCP) Service Account"
  Regex = "\"type\": \"service_account\""
  File = ""
  Path = ""
  Tags = ["key", "Google"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Heroku API key"
  Regex = "(?i)heroku(.{0,20})?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
  File = ""
  Path = ""
  Tags = ["key", "Heroku"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "MailChimp API key"
  Regex = "(?i)(mailchimp|mc)(.{0,20})?[0-9a-f]{32}-us[0-9]{1,2}"
  File = ""
  Path = ""
  Tags = ["key", "Mailchimp"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Mailgun API key"
  Regex = "((?i)(mailgun|mg)(.{0,20})?)?key-[0-9a-z]{32}"
  File = ""
  Path = ""
  Tags = ["key", "Mailgun"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "PayPal Braintree access token"
  Regex = "access_token\\$production\\$[0-9a-z]{16}\\$[0-9a-f]{32}"
  File = ""
  Path = ""
  Tags = ["key", "Paypal"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Picatic API key"
  Regex = "sk_live_[0-9a-z]{32}"
  File = ""
  Path = ""
  Tags = ["key", "Picatic"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "SendGrid API Key"
  Regex = "SG\\.[\\w_]{16,32}\\.[\\w_]{16,64}"
  File = ""
  Path = ""
  Tags = ["key", "SendGrid"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Slack Webhook"
  Regex = "https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}"
  File = ""
  Path = ""
  Tags = ["key", "slack"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Stripe API key"
  Regex = "(?i)stripe(.{0,20})?[sr]k_live_[0-9a-zA-Z]{24}"
  File = ""
  Path = ""
  Tags = ["key", "Stripe"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Square access token"
  Regex = "sq0atp-[0-9A-Za-z\\-_]{22}"
  File = ""
  Path = ""
  Tags = ["key", "square"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Square OAuth secret"
  Regex = "sq0csp-[0-9A-Za-z\\\\-_]{43}"
  File = ""
  Path = ""
  Tags = ["key", "square"]
  [Rules.AllowList]
    Description = ""

[[Rules]]
  Description = "Twilio API key"
  Regex = "(?i)twilio(.{0,20})?SK[0-9a-f]{32}"
  File = ""
  Path = ""
  Tags = ["key", "twilio"]
  [Rules.AllowList]
    Description = ""
